name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

# Autolabeler inspects each PR's title so you don't have to manually label every PR. 
autolabeler:
  - label: "major"
    title:
      - "/^breaking(\\(.*\\))?!:/i"
    body:
      - "/BREAKING CHANGE/i"
  - label: "minor"
    title:
      - "/^feat(\\(.*\\))?:/i"
  - label: "patch"
    title:
      - "/^fix(\\(.*\\))?:/i"
      - "/^perf(\\(.*\\))?:/i"
  - label: "documentation"
    title:
      - "/^docs(\\(.*\\))?:/i"
  - label: "chore"
    title:
      - "/^chore(\\(.*\\))?:/i"
      - "/^ci(\\(.*\\))?:/i"
      - "/^refactor(\\(.*\\))?:/i"
      - "/^test(\\(.*\\))?:/i"

# Section configurations for what visibly appears in your release notes changelog
categories:
  - title: '🚨 Breaking Changes'
    labels:
      - 'major'
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'ci'
      - 'github-actions'
      - 'docker'
      - 'python'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'

# Prevents matching PRs from appearing in the release notes changelog text
exclude-labels:
  - 'skip-changelog'

# Handles calculations for tracking major, minor, and patch bumps
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: 'patch'

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
