# Description: Configures project tooling or services for MultiProtocolGateway.
# File: ruff.toml
#
# Copyright 2026 Kevin Burke
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://apache.org
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

line-length = 88
indent-width = 4
target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.

select = ["BLE", "C", "DTZ", "E", "EM", "F", "FA", "FBT", "G", "I", "LOG", "S", "TRY", "W"]

#select = ["ALL"]
ignore = [
"BLE001",
"C901",
"D",
"EM101",
"E501",
"FBT001", "FBT002",
"N",
"RUF",
"S101",
"TRY003",
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
