name: Release

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
    branches:
      - master

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write   # to create/update the draft release
      pull-requests: write   # to autolabel PRs
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
